services:
  - type: web
    name: games-app-spa
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"